"""empty message

Revision ID: 1c66c4ce6c01
Revises:
Create Date: 2026-04-29 11:34:07.420840

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1c66c4ce6c01"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks",
        sa.Column("task_id", sa.String(length=48), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("instruction_source", sa.Text(), nullable=False),
        sa.Column("normalized_instruction", sa.Text(), nullable=True),
        sa.Column("target_working_directory", sa.Text(), nullable=True),
        sa.Column(
            "execution_mode",
            sa.Enum(
                "one_time",
                "recurring",
                name="executionmode",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column(
            "task_status",
            sa.Enum(
                "scheduled",
                "paused",
                "running",
                "completed",
                "failed",
                "canceled",
                "archived",
                name="taskstatus",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("template_id", sa.String(length=48), nullable=True),
        sa.Column(
            "executor",
            sa.Enum(
                "claude_code",
                "codex",
                "opencode",
                "kimi_code",
                "debug_printer",
                name="executorname",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("task_id"),
    )
    op.create_table(
        "templates",
        sa.Column("template_id", sa.String(length=48), nullable=False),
        sa.Column("name", sa.String(length=240), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("instruction_source", sa.Text(), nullable=False),
        sa.Column("default_task_title", sa.String(length=240), nullable=True),
        sa.Column("default_target_working_directory", sa.Text(), nullable=True),
        sa.Column(
            "default_execution_mode",
            sa.Enum(
                "one_time",
                "recurring",
                name="executionmode",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column(
            "default_schedule_type",
            sa.Enum(
                "single_run",
                "recurring_rule",
                name="scheduletype",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("default_planned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("default_recurrence_rule", sa.Text(), nullable=True),
        sa.Column("default_recurrence_timezone", sa.String(length=128), nullable=True),
        sa.Column(
            "default_executor",
            sa.Enum(
                "claude_code",
                "codex",
                "opencode",
                "kimi_code",
                "debug_printer",
                name="executorname",
                native_enum=False,
                length=64,
            ),
            nullable=True,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("template_id"),
    )
    op.create_index(
        "ix_templates_archived_at_created_at",
        "templates",
        ["archived_at", "created_at"],
        unique=False,
    )
    op.create_table(
        "schedules",
        sa.Column("schedule_id", sa.String(length=48), nullable=False),
        sa.Column("task_id", sa.String(length=48), nullable=False),
        sa.Column(
            "schedule_type",
            sa.Enum(
                "single_run",
                "recurring_rule",
                name="scheduletype",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column(
            "schedule_status",
            sa.Enum(
                "pending",
                "active",
                "paused",
                "completed",
                "canceled",
                name="schedulestatus",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("planned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("recurrence_rule", sa.Text(), nullable=True),
        sa.Column("recurrence_timezone", sa.String(length=128), nullable=True),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_materialized_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("external_schedule_ref", sa.String(length=240), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.task_id"],
        ),
        sa.PrimaryKeyConstraint("schedule_id"),
        sa.UniqueConstraint("task_id", name="uq_schedules_task_id_vertical_slice"),
    )
    op.create_index("ix_schedules_task_id", "schedules", ["task_id"], unique=False)
    op.create_table(
        "occurrence_overrides",
        sa.Column("occurrence_override_id", sa.String(length=48), nullable=False),
        sa.Column("task_id", sa.String(length=48), nullable=False),
        sa.Column("schedule_id", sa.String(length=48), nullable=False),
        sa.Column("original_occurrence_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("override_occurrence_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("override_instruction_delta", sa.Text(), nullable=True),
        sa.Column(
            "override_status",
            sa.Enum(
                "active",
                "canceled",
                name="occurrenceoverridestatus",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["schedules.schedule_id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.task_id"],
        ),
        sa.PrimaryKeyConstraint("occurrence_override_id"),
        sa.UniqueConstraint(
            "schedule_id",
            "original_occurrence_at",
            name="uq_occurrence_overrides_schedule_original",
        ),
    )
    op.create_index(
        "ix_occurrence_overrides_schedule_id",
        "occurrence_overrides",
        ["schedule_id"],
        unique=False,
    )
    op.create_index(
        "ix_occurrence_overrides_task_id",
        "occurrence_overrides",
        ["task_id"],
        unique=False,
    )
    op.create_table(
        "runs",
        sa.Column("run_id", sa.String(length=48), nullable=False),
        sa.Column("task_id", sa.String(length=48), nullable=False),
        sa.Column("schedule_id", sa.String(length=48), nullable=True),
        sa.Column(
            "run_status",
            sa.Enum(
                "planned",
                "queued",
                "running",
                "completed",
                "failed",
                "canceled",
                name="runstatus",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("planned_start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actual_start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("result_summary", sa.Text(), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("external_execution_ref", sa.String(length=240), nullable=True),
        sa.Column("occurrence_key", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["schedules.schedule_id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.task_id"],
        ),
        sa.PrimaryKeyConstraint("run_id"),
        sa.UniqueConstraint(
            "schedule_id", "occurrence_key", name="uq_runs_schedule_occurrence_key"
        ),
    )
    op.create_index(
        "ix_runs_history_status_finished_at",
        "runs",
        ["run_status", "finished_at"],
        unique=False,
    )
    op.create_index("ix_runs_schedule_id", "runs", ["schedule_id"], unique=False)
    op.create_index("ix_runs_task_id", "runs", ["task_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_runs_task_id", table_name="runs")
    op.drop_index("ix_runs_schedule_id", table_name="runs")
    op.drop_index("ix_runs_history_status_finished_at", table_name="runs")
    op.drop_table("runs")
    op.drop_index("ix_occurrence_overrides_task_id", table_name="occurrence_overrides")
    op.drop_index(
        "ix_occurrence_overrides_schedule_id", table_name="occurrence_overrides"
    )
    op.drop_table("occurrence_overrides")
    op.drop_index("ix_schedules_task_id", table_name="schedules")
    op.drop_table("schedules")
    op.drop_index("ix_templates_archived_at_created_at", table_name="templates")
    op.drop_table("templates")
    op.drop_table("tasks")
    # ### end Alembic commands ###
