"""add template

Revision ID: 60b021740156
Revises: e348c4a1d6fb
Create Date: 2026-04-26 08:57:27.591516

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "60b021740156"
down_revision = "e348c4a1d6fb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "templates",
        sa.Column("template_id", sa.String(length=48), nullable=False),
        sa.Column("name", sa.String(length=240), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("instruction_source", sa.Text(), nullable=False),
        sa.Column("default_task_title", sa.String(length=240), nullable=True),
        sa.Column("default_target_working_directory", sa.Text(), nullable=True),
        sa.Column(
            "default_execution_mode",
            sa.Enum(
                "one_time",
                "recurring",
                name="executionmode",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column(
            "default_schedule_type",
            sa.Enum(
                "single_run",
                "recurring_rule",
                name="scheduletype",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("default_planned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("default_recurrence_rule", sa.Text(), nullable=True),
        sa.Column("default_recurrence_timezone", sa.String(length=128), nullable=True),
        sa.Column(
            "default_executor",
            sa.Enum(
                "claude_code",
                "debug_printer",
                name="executorname",
                native_enum=False,
                length=64,
            ),
            nullable=True,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("template_id"),
    )
    op.create_index(
        "ix_templates_archived_at_created_at",
        "templates",
        ["archived_at", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_templates_archived_at_created_at", table_name="templates")
    op.drop_table("templates")
    # ### end Alembic commands ###
