"""add run events

Revision ID: 72fe38e2c219
Revises: 1c66c4ce6c01
Create Date: 2026-04-30 11:31:20.596225

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "72fe38e2c219"
down_revision: str | Sequence[str] | None = "1c66c4ce6c01"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "run_events",
        sa.Column("run_event_id", sa.String(length=48), nullable=False),
        sa.Column("run_id", sa.String(length=48), nullable=False),
        sa.Column("task_id", sa.String(length=48), nullable=False),
        sa.Column("schedule_id", sa.String(length=48), nullable=True),
        sa.Column("event_type", sa.String(length=96), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("temporal_workflow_id", sa.String(length=240), nullable=True),
        sa.Column("temporal_workflow_run_id", sa.String(length=240), nullable=True),
        sa.Column("activity_type", sa.String(length=120), nullable=True),
        sa.Column("activity_attempt", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.run_id"],
        ),
        sa.PrimaryKeyConstraint("run_event_id"),
    )
    op.create_index(
        "ix_run_events_run_id_created_at",
        "run_events",
        ["run_id", "created_at", "run_event_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_run_events_run_id_created_at", table_name="run_events")
    op.drop_table("run_events")
    # ### end Alembic commands ###
