"""add_occurrence_overrides

Revision ID: 7dfe3e573074
Revises: d6faeb207fab
Create Date: 2026-04-27 13:25:40.235269

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7dfe3e573074"
down_revision = "d6faeb207fab"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "occurrence_overrides",
        sa.Column("occurrence_override_id", sa.String(length=48), nullable=False),
        sa.Column("task_id", sa.String(length=48), nullable=False),
        sa.Column("schedule_id", sa.String(length=48), nullable=False),
        sa.Column("original_occurrence_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("override_occurrence_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("override_instruction_delta", sa.Text(), nullable=True),
        sa.Column(
            "override_status",
            sa.Enum(
                "active",
                "canceled",
                name="occurrenceoverridestatus",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["schedules.schedule_id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.task_id"],
        ),
        sa.PrimaryKeyConstraint("occurrence_override_id"),
        sa.UniqueConstraint(
            "schedule_id",
            "original_occurrence_at",
            name="uq_occurrence_overrides_schedule_original",
        ),
    )
    op.create_index(
        "ix_occurrence_overrides_schedule_id",
        "occurrence_overrides",
        ["schedule_id"],
        unique=False,
    )
    op.create_index(
        "ix_occurrence_overrides_task_id",
        "occurrence_overrides",
        ["task_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_occurrence_overrides_task_id", table_name="occurrence_overrides")
    op.drop_index(
        "ix_occurrence_overrides_schedule_id", table_name="occurrence_overrides"
    )
    op.drop_table("occurrence_overrides")
    # ### end Alembic commands ###
