"""init

Revision ID: b4272fbe1936
Revises:
Create Date: 2026-04-25 17:13:27.631593

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b4272fbe1936"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks",
        sa.Column("task_id", sa.String(length=48), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("instruction_source", sa.Text(), nullable=False),
        sa.Column("normalized_instruction", sa.Text(), nullable=True),
        sa.Column(
            "execution_mode",
            sa.Enum(
                "one_time",
                "recurring",
                name="executionmode",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column(
            "task_status",
            sa.Enum(
                "scheduled",
                "paused",
                "running",
                "completed",
                "failed",
                "canceled",
                "archived",
                name="taskstatus",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("template_id", sa.String(length=48), nullable=True),
        sa.Column(
            "executor",
            sa.Enum(
                "claude_code",
                "debug_printer",
                name="executorname",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("task_id"),
    )
    op.create_table(
        "schedules",
        sa.Column("schedule_id", sa.String(length=48), nullable=False),
        sa.Column("task_id", sa.String(length=48), nullable=False),
        sa.Column(
            "schedule_type",
            sa.Enum(
                "single_run",
                "recurring_rule",
                name="scheduletype",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column(
            "schedule_status",
            sa.Enum(
                "pending",
                "active",
                "paused",
                "completed",
                "canceled",
                name="schedulestatus",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("planned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("recurrence_rule", sa.Text(), nullable=True),
        sa.Column("recurrence_timezone", sa.String(length=128), nullable=True),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_materialized_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("external_schedule_ref", sa.String(length=240), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.task_id"],
        ),
        sa.PrimaryKeyConstraint("schedule_id"),
        sa.UniqueConstraint("task_id", name="uq_schedules_task_id_vertical_slice"),
    )
    op.create_index("ix_schedules_task_id", "schedules", ["task_id"], unique=False)
    op.create_table(
        "runs",
        sa.Column("run_id", sa.String(length=48), nullable=False),
        sa.Column("task_id", sa.String(length=48), nullable=False),
        sa.Column("schedule_id", sa.String(length=48), nullable=True),
        sa.Column(
            "run_status",
            sa.Enum(
                "planned",
                "queued",
                "running",
                "completed",
                "failed",
                "canceled",
                name="runstatus",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("planned_start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actual_start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("result_summary", sa.Text(), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("external_execution_ref", sa.String(length=240), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["schedules.schedule_id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.task_id"],
        ),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_index("ix_runs_schedule_id", "runs", ["schedule_id"], unique=False)
    op.create_index("ix_runs_task_id", "runs", ["task_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_runs_task_id", table_name="runs")
    op.drop_index("ix_runs_schedule_id", table_name="runs")
    op.drop_table("runs")
    op.drop_index("ix_schedules_task_id", table_name="schedules")
    op.drop_table("schedules")
    op.drop_table("tasks")
    # ### end Alembic commands ###
