# pyright: reportUnusedCallResult=false

"""add executor profile reasoning level

Revision ID: b9b31cf5babf
Revises: 1c66c4ce6c01
Create Date: 2026-05-30 20:44:11.242980

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b9b31cf5babf"
down_revision: str | Sequence[str] | None = "1c66c4ce6c01"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profile_validation_handoffs",
        sa.Column("handoff_id", sa.String(length=48), nullable=False),
        sa.Column("executor", sa.String(length=64), nullable=False),
        sa.Column("default_model", sa.String(length=160), nullable=True),
        sa.Column("reasoning_level", sa.String(length=160), nullable=True),
        sa.Column("env", sa.JSON(), nullable=False),
        sa.Column("secret_env", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("handoff_id"),
    )
    op.create_index(
        "ix_profile_validation_handoffs_expires_at",
        "profile_validation_handoffs",
        ["expires_at"],
        unique=False,
    )
    op.add_column(
        "executor_profiles",
        sa.Column("reasoning_level", sa.String(length=160), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("executor_profiles", "reasoning_level")
    op.drop_index(
        "ix_profile_validation_handoffs_expires_at",
        table_name="profile_validation_handoffs",
    )
    op.drop_table("profile_validation_handoffs")
    # ### end Alembic commands ###
