"""add executor profiles

Revision ID: bdf04818de9e
Revises: 72fe38e2c219
Create Date: 2026-05-02 11:37:38.881547

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bdf04818de9e"
down_revision: str | Sequence[str] | None = "72fe38e2c219"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "executor_profiles",
        sa.Column("profile_id", sa.String(length=48), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "executor",
            sa.Enum(
                "claude_code",
                "codex",
                "kimi_code",
                "debug_printer",
                name="executorname",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("default_model", sa.String(length=160), nullable=True),
        sa.Column("env", sa.JSON(), nullable=False),
        sa.Column("secret_env", sa.JSON(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("profile_id"),
    )
    op.create_index(
        "ix_executor_profiles_archived_at",
        "executor_profiles",
        ["archived_at"],
        unique=False,
    )
    op.create_index(
        "ix_executor_profiles_executor_default",
        "executor_profiles",
        ["executor", "is_default"],
        unique=False,
    )
    op.add_column(
        "tasks", sa.Column("executor_profile_id", sa.String(length=48), nullable=True)
    )
    op.create_foreign_key(
        "fk_tasks_executor_profile_id_executor_profiles",
        "tasks",
        "executor_profiles",
        ["executor_profile_id"],
        ["profile_id"],
    )
    op.add_column(
        "templates",
        sa.Column("default_executor_profile_id", sa.String(length=48), nullable=True),
    )
    op.create_foreign_key(
        "fk_templates_default_executor_profile_id_executor_profiles",
        "templates",
        "executor_profiles",
        ["default_executor_profile_id"],
        ["profile_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_templates_default_executor_profile_id_executor_profiles",
        "templates",
        type_="foreignkey",
    )
    op.drop_column("templates", "default_executor_profile_id")
    op.drop_constraint(
        "fk_tasks_executor_profile_id_executor_profiles",
        "tasks",
        type_="foreignkey",
    )
    op.drop_column("tasks", "executor_profile_id")
    op.drop_index(
        "ix_executor_profiles_executor_default", table_name="executor_profiles"
    )
    op.drop_index("ix_executor_profiles_archived_at", table_name="executor_profiles")
    op.drop_table("executor_profiles")
    # ### end Alembic commands ###
