"""add override schedule columns

Revision ID: c6b90bd3d7fe
Revises: bdf04818de9e
Create Date: 2026-05-11 13:29:26.112930

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c6b90bd3d7fe"
down_revision: str | Sequence[str] | None = "bdf04818de9e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "occurrence_overrides",
        sa.Column("rescheduled_run_id", sa.String(length=48), nullable=True),
    )
    op.add_column(
        "occurrence_overrides",
        sa.Column("external_schedule_ref", sa.String(length=240), nullable=True),
    )
    op.create_foreign_key(
        None, "occurrence_overrides", "runs", ["rescheduled_run_id"], ["run_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "occurrence_overrides", type_="foreignkey")
    op.drop_column("occurrence_overrides", "external_schedule_ref")
    op.drop_column("occurrence_overrides", "rescheduled_run_id")
    # ### end Alembic commands ###
