"""add history index

Revision ID: e348c4a1d6fb
Revises: 7dd6bb6c746f
Create Date: 2026-04-26 08:40:01.374480

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "e348c4a1d6fb"
down_revision = "7dd6bb6c746f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_runs_history_status_finished_at",
        "runs",
        ["run_status", "finished_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_runs_history_status_finished_at", table_name="runs")
    # ### end Alembic commands ###
