"""add recurring run occurrence key

Revision ID: ee22c65b802e
Revises: 60b021740156
Create Date: 2026-04-26 11:09:49.579827

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ee22c65b802e"
down_revision = "60b021740156"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "runs", sa.Column("occurrence_key", sa.String(length=32), nullable=True)
    )
    op.create_unique_constraint(
        "uq_runs_schedule_occurrence_key", "runs", ["schedule_id", "occurrence_key"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_runs_schedule_occurrence_key", "runs", type_="unique")
    op.drop_column("runs", "occurrence_key")
    # ### end Alembic commands ###
